/**
 * 👑 King RANUX PRO – User Configuration (cleaned)
 */

module.exports = {

  // 🔐 WhatsApp Session ID (leave empty when using DB-based sessions)
  // If you still want to use a single legacy SESSION_ID, you can set it via
  // environment variable `SESSION_ID` or paste a base64 session string here.
  SESSION_ID: process.env.SESSION_ID || "𝐊𝐢𝐧𝐠 𝐑𝐀𝐍𝐔𝐗 ᴾʳᵒ ~eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiV09CdWMvTWpyaGl2d2xhUnd5cGd4VWhvTVBEMkI1T296MGl0RlU0dUlGdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOWE2Wko4YnV3VzFwaE8za3czZjhrc3JjdkhabnlhRU5OR3MrU0xYYVozUT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJrQjNsVURWbW4vNkJobFplZ1RoODJPamVYUzNIU05xbUpjMUFMRmxhWDFJPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJTQkRYaGdEYTJtK094VE1EUHJWb2pxRnQ2dzh0cmVuaHpBMDJJOHVzK0dvPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IldERmRRNjBRM1o4RXc4SmZyZGVjMU9mTTdtK1FnakNWY293d0x6K210WGs9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkF5QmhqWC9MOCs5S3NEUVpCZ3VkdW9WaVF0bXFCQzVudWVMcTB1MUFFMDg9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQUY2bDlOOGFjRTFzdjFOcXNiNWJBQ0tvdzVHNVZNazArdUlXSG02QkdtTT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMjJiQXVOenRFc0J6Z2NIMXowaFNxclY0SEp1ckRxa0VRTGRoV0JSa3NHQT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Imp6dVlpTHpZVUJ4NitFM0NzWUhIZ05BUU1jTjYzek14bmV2SHA3OEF5WnhnWnhCdklHb2xCdEZUcnFRODFxUmtmK1V1V3dnRmNQRW9PNDd4Wk11cEJRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjMyLCJhZHZTZWNyZXRLZXkiOiJTWnNvNDN1YjdONkJpK0VTUzV4OTNqTURiSEdjOXRJb05xQ01uN3R2Y1E4PSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6Ijk0NzI2ODgwNzg0QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjpmYWxzZSwiaWQiOiJBNTg2MkM4RERCMjg5MEVDQTBENTY0MDc3RTJERTIwMCIsInBhcnRpY2lwYW50IjoiIiwiYWRkcmVzc2luZ01vZGUiOiJwbiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzcwOTcxMTgyfSx7ImtleSI6eyJyZW1vdGVKaWQiOiI5NDcyNjg4MDc4NEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6ZmFsc2UsImlkIjoiQTVCNTU1NzEwNDlFNzIyQzY2RUE1NzQ4MENENjA3QUYiLCJwYXJ0aWNpcGFudCI6IiIsImFkZHJlc3NpbmdNb2RlIjoicG4ifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc3MDk3MTE4Mn0seyJrZXkiOnsicmVtb3RlSmlkIjoiOTQ3MjY4ODA3ODRAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOmZhbHNlLCJpZCI6IkE1OTJDN0VEQTk4NjdEM0JGNEVGMTdGRkE0QTJBRkRBIiwicGFydGljaXBhbnQiOiIiLCJhZGRyZXNzaW5nTW9kZSI6InBuIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NzA5NzExODN9LHsia2V5Ijp7InJlbW90ZUppZCI6Ijk0NzI2ODgwNzg0QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjpmYWxzZSwiaWQiOiJBNUU0NjE1QTVDMTAwOTA3ODc1RTc2RTk4MzBBODQzQiIsInBhcnRpY2lwYW50IjoiIiwiYWRkcmVzc2luZ01vZGUiOiJwbiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzcwOTcxMTgzfSx7ImtleSI6eyJyZW1vdGVKaWQiOiI5NDcyNjg4MDc4NEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6ZmFsc2UsImlkIjoiQTU5MTMyMzFBQ0JDMkU0QzdCQjI3NzBDOUU5RjRCRTUiLCJwYXJ0aWNpcGFudCI6IiIsImFkZHJlc3NpbmdNb2RlIjoicG4ifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc3MDk3MTE4Nn0seyJrZXkiOnsicmVtb3RlSmlkIjoiOTQ3MjY4ODA3ODRAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOmZhbHNlLCJpZCI6IkE1NThBN0U0NkM5Rjk1N0MyNjJGREFBMjNCRERCMDkwIiwicGFydGljaXBhbnQiOiIiLCJhZGRyZXNzaW5nTW9kZSI6InBuIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NzA5NzExODl9XSwibmV4dFByZUtleUlkIjo4MTMsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjo4MTMsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sInJlZ2lzdGVyZWQiOnRydWUsInBhaXJpbmdDb2RlIjoiN01NSkNIVjQiLCJtZSI6eyJpZCI6Ijk0NzI2ODgwNzg0OjY4QHMud2hhdHNhcHAubmV0IiwibmFtZSI6IvCdk5zwnZOhLiDwnZOh8J2TqvCdk7fwnZO88J2TqvCdk7vwnZOqIPCdk5PwnZOu8J2Tv/Cdk7fwnZOq8J2TvfCdk7EiLCJsaWQiOiIyNDk0ODIxMzQ0NDIxNjQ6NjhAbGlkIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNJbjJ4YjhCRUtiQXU4d0dHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJYSmFUaHJQUFo0SXNnSHBpT0FKcTE0bHFESlIrVXFEMkxNYjVRd01FNWlRPSIsImFjY291bnRTaWduYXR1cmUiOiJPZjRYZzdYdS8yWDFDTkFXYXJQdVhrd2s5ZWtiVUEwa004M25LUkdNTXAvV2s4Y3hoaFpSY0pDR1ZVdnh2WlB4a3plWDVvdmdVSklhSGNKalNYdHZEUT09IiwiZGV2aWNlU2lnbmF0dXJlIjoiakt1dmVURlAyQ0FYVCtZTFJhRUh4aUJUU09aR0loLzVLcjJqZ2ttcjArQlRQeUt5OGp5alZDNlpLS1Zqek9UdmZMWFlKWlFwT0ZkeUg0UWJlbDFHQUE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNDk0ODIxMzQ0NDIxNjQ6NjhAbGlkIiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlZ5V2s0YXp6MmVDTElCNllqZ0NhdGVKYWd5VWZsS2c5aXpHK1VNREJPWWsifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJyb3V0aW5nSW5mbyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNBVUlFZ2dDIn0sImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc3MDk3MTE4MCwibGFzdFByb3BIYXNoIjoiMUs0aEg0IiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFQNmQifQ==",

  // ===============================
  // 🤖 BOT MODE SYSTEM
  // public  = groups + inbox
  // group   = groups only
  // inbox   = inbox only
  // private = owner + sudo only
  // ===============================
  MODE: process.env.MODE || "public",

  // ===============================
  // 📌 STATUS AUTOMATION
  // ===============================
  AUTO_STATUS_SEEN: true,
  AUTO_STATUS_REACT: false,
  AUTO_STATUS_FORWARD: false,

  // ===============================
  // 🛡️ ANTI DELETE
  // ===============================
  ANTI_DELETE: true,

  // ===============================
  // ⚙️ GENERAL
  // ===============================
  PREFIX: process.env.PREFIX || ",",

  // ===============================
  // 🎬 MOVIE PLUGIN FOOTER
  // ===============================
  MOVIE_FOOTER_TEXT: "𝓜𝓡. 𝓡𝓪𝓷𝓼𝓪𝓻𝓪 𝓓𝓮𝓿𝓷𝓪𝓽𝓱",
  
  BOT_OWNER: '94726880784',
};
