/**
 * 👑 King RANUX PRO – User Configuration (cleaned)
 */

module.exports = {

  // 🔐 WhatsApp Session ID (leave empty when using DB-based sessions)
  // If you still want to use a single legacy SESSION_ID, you can set it via
  // environment variable `SESSION_ID` or paste a base64 session string here.
  SESSION_ID: process.env.SESSION_ID || "𝐊𝐢𝐧𝐠 𝐑𝐀𝐍𝐔𝐗 ᴾʳᵒ ~eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoia01WWUhUYUFLeVZRaEYxVGFia29lcmdXNWFGUkRsZGs2QnpGZjR5TURsWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiR0JLY3k4L0RtdjNLVTBiaUtYQSt4Z2FQZFJOWEorYnJzRjNROHhUZ2tHQT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJTQVp4VjZ2UlpyWE9rb1NzSHBtM3hhWVNqdXV0Y21zNjU1ZzhNekZUOFdZPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJOS2MvUzUvbU12RkZmUjl3K2lqalJpU09QWUNqY2tNREhzVFZqMTR1STNJPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlFCQnVQdU1DK0l5UVJaMHpiSzNpYklaa3JWQ01qYUJUUFJUY3dxY0VCWGc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjllNXJYR2pOMm5pdDd2akduWjlXL2FpMkRxeFdWSTFQU000dFVhUVF2anM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoia0pRSjN6Yk5qYzBLanhBMzhkVStnUi8vM3lkK1NsZHB1dkkyeTQya0psWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibXkvWTJmR2ExUHdUTC96Nm1XV1hrVmh3VzlJZWZ1Qk5qdTYxeEY2RDRDaz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im1BZVllU0VhSzAvUnpWRkdyL1dUMHk2TC9RVGpaNDJ3dGtmRllENGNWTDkwTVlXbTBWYzZ2anljMWw5TXhibFZ6UG5yVHljaGlOcXZJelhQdzNTcWh3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MzYsImFkdlNlY3JldEtleSI6IjZUQmx4MTVwblFyTFdJRlpQMWR3dkYvWU5PNjZjRStaTnhRbm1WUW40Y3c9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiOTQ3MjY4ODA3ODRAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOmZhbHNlLCJpZCI6IkE1N0JBRjhDNEQyRjI0QkE2MUY3QzJFOTZFNEZEQzk5IiwicGFydGljaXBhbnQiOiIiLCJhZGRyZXNzaW5nTW9kZSI6InBuIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NzEwMzA2ODl9LHsia2V5Ijp7InJlbW90ZUppZCI6Ijk0NzI2ODgwNzg0QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjpmYWxzZSwiaWQiOiJBNUJCNTE3MUQ0NzhGM0ZEOTdGQUFENjBBNDQ5MzlBRCIsInBhcnRpY2lwYW50IjoiIiwiYWRkcmVzc2luZ01vZGUiOiJwbiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzcxMDMwNjg5fSx7ImtleSI6eyJyZW1vdGVKaWQiOiI5NDcyNjg4MDc4NEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6ZmFsc2UsImlkIjoiQTVCNzFGQkJCODM3MEZDMjQzREM2RTkwOTJFQjEyMjYiLCJwYXJ0aWNpcGFudCI6IiIsImFkZHJlc3NpbmdNb2RlIjoicG4ifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc3MTAzMDY4OX0seyJrZXkiOnsicmVtb3RlSmlkIjoiOTQ3MjY4ODA3ODRAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOmZhbHNlLCJpZCI6IkE1QjQ0MUYwQ0NCQzRCMjU1OTMwOEFDQkZDNUYwRURBIiwicGFydGljaXBhbnQiOiIiLCJhZGRyZXNzaW5nTW9kZSI6InBuIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NzEwMzA2OTF9LHsia2V5Ijp7InJlbW90ZUppZCI6Ijk0NzI2ODgwNzg0QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjpmYWxzZSwiaWQiOiJBNTM3RDgxMzU1QTI4RjI5RjUyMzc3QkQ1QjFEMEY2OCIsInBhcnRpY2lwYW50IjoiIiwiYWRkcmVzc2luZ01vZGUiOiJwbiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzcxMDMwNjkyfV0sIm5leHRQcmVLZXlJZCI6ODEzLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6ODEzLCJhY2NvdW50U3luY0NvdW50ZXIiOjEsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6IjNBWlBFUDhGIiwibWUiOnsiaWQiOiI5NDcyNjg4MDc4NDo3MUBzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiLwnZOc8J2ToS4g8J2TofCdk6rwnZO38J2TvPCdk6rwnZO78J2TqiDwnZOT8J2TrvCdk7/wnZO38J2TqvCdk73wnZOxIiwibGlkIjoiMjQ5NDgyMTM0NDQyMTY0OjcxQGxpZCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDSW4yeGI4QkVKdVJ2OHdHR0FRZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiWEphVGhyUFBaNElzZ0hwaU9BSnExNGxxREpSK1VxRDJMTWI1UXdNRTVpUT0iLCJhY2NvdW50U2lnbmF0dXJlIjoiWWJITEN2U1R1OUZXaGZxTHRrWWF0SU1ubVN0UVA3SXNKakQ3K3FFd3RZYW9Ud2EzK01PRElseU9ZdTJZM2dnOC9yOCtMRStpNXd0UVpvWmY1THRmQnc9PSIsImRldmljZVNpZ25hdHVyZSI6IlJLbUx4dUMvT1Y4ejIvSmtDMllGUm9HK2d1ZkN0WDYxK2JQcmtWa2c5Yi9EZ0RDY2wwY3NQcDVLWXd2OFRmSE5RT29ua0h2ZFpFNjRDb1RNVkdHVGhRPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjQ5NDgyMTM0NDQyMTY0OjcxQGxpZCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJWeVdrNGF6ejJlQ0xJQjZZamdDYXRlSmFneVVmbEtnOWl6RytVTURCT1lrIn19XSwicGxhdGZvcm0iOiJzbWJhIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQVVJRWdnQyJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NzEwMzA2ODcsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBUDZlIiwibGFzdFByb3BIYXNoIjoiMUs0aEg0In0=",

  // ===============================
  // 🤖 BOT MODE SYSTEM
  // public  = groups + inbox
  // group   = groups only
  // inbox   = inbox only
  // private = owner + sudo only
  // ===============================
  MODE: process.env.MODE || "public",

  // ===============================
  // 📌 STATUS AUTOMATION
  // ===============================
  AUTO_STATUS_SEEN: true,
  AUTO_STATUS_REACT: false,
  AUTO_STATUS_FORWARD: false,

  // ===============================
  // 🛡️ ANTI DELETE
  // ===============================
  ANTI_DELETE: true,

  // ===============================
  // ⚙️ GENERAL
  // ===============================
  PREFIX: process.env.PREFIX || ",",

  // ===============================
  // 🎬 MOVIE PLUGIN FOOTER
  // ===============================
  MOVIE_FOOTER_TEXT: "𝓜𝓡. 𝓡𝓪𝓷𝓼𝓪𝓻𝓪 𝓓𝓮𝓿𝓷𝓪𝓽𝓱",
  
  BOT_OWNER: '94726880784',
};
